version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
      - ./yarn.lock:/app/yarn.lock
      - ./client:/app
    restart: on-failure
