version: '3'
services:
  client:
    build:
      context: ./client/
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./client/package.json:/app/package.json
      - ./client/node_modules:/app/node_modules
      - ./client/package-lock.json:/app/package-lock.json
      - ./client:/app
    restart: on-failure
