version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node-modules
      - ./client:/app
    restart: on-failure
